#-------------------------------
# General Site Settings

name: chengin dev
title: Chengin Dev | Home 
description: My name is Tim Chen. I'm a dad, a software engineer and an aspiring traveling foodie.
baseurl:  # the subpath of your site, e.g. /blog
url: https://chengin.com # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
author-name:   Tim Chen
author-avatar: 02.jpg

#-------------------------------
# Contact links
social:
  github: https://github.com/h3adache
  instagram: https://www.instagram.com/h3adache
  linkedin: https://www.linkedin.com/in/chengt
  # facebook:  # https://facebook.com/ 
  # twitter:   # https://twitter.com/
  # pinterest: # https://www.pinterest.com/


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # mr-brown # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
